services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ../app:/app
  app:
    build: services/php
    volumes:
      - ../app:/app
  db:
    image: mariadb:latest
    environment:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "cv_db"
    # env_file: .env
    #env_file:
    # - .env
    volumes:
      - mysqldata:/var/lib/mysql
      - .:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"

volumes:
  mysqldata: {}